baseurl = "/"
languageCode = "en-us"
title = "j3rmbadger.com"
theme = "hugo-classic"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
enableEmoji = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 2
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3
[[menu.feed]]
    name = "Subscribe"
    url = "/index.xml"

[params]
    description = "All things incident response, all things honeybadger, j3rmbadger.com"
    footer = "Open-Source | [Github](https://github.com/jermdw) | [Twitter](https://twitter.com/h0neybdg3r)"
    custom_css = ["css/theme-override.css"]
